# Setup version numbers
set(RESBOS_VERSION_MAJOR 2)
set(RESBOS_VERSION_MINOR 0)
set(RESBOS_VERSION_PATCH 0)
set(RESBOS_VERSION "${RESBOS_VERSION_MAJOR}.${RESBOS_VERSION_MINOR}.${RESBOS_VERSION_PATCH}")

# Use CPack to package the source
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "ResBos2: Transverse Momentum Resummation Event Generator")
SET(CPACK_PACKAGE_VENDOR "Joshua Isaacson")
SET(CPACK_PACKAGE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
SET(CPACK_PACKAGE_VERSION_MAJOR ${RESBOS_VERSION_MAJOR})
SET(CPACK_PACKAGE_VERSION_MINOR ${RESBOS_VERSION_MINOR})
SET(CPACK_PACKAGE_VERSION_PATCH ${RESBOS_VERSION_PATCH})
# SET(CPACK_PACKAGE_INSTALL_DIRECTORY "CMake ${CMake_VERSION_MAJOR}.${CMake_VERSION_MINOR}")
SET(CPACK_SOURCE_GENERATOR "TGZ;ZIP;BZ2")
set(CPACK_SOURCE_IGNORE_FILES 
    /.git
    /dist
    /.*build*
    /\\\\.DS_Store
    /NonPert
    /tmp
    /.vim
    /.clangd
    /CMakeFiles
    /OrganizationDetails.md
)
include(CPack)

