# List of all program options
option(USE-ROOT "Enable histogramming with ROOT" OFF)
option(USE-YODA "Enable histogramming with YODA" OFF)
option(USE-GZIP "Enable the use of gzip for reading and writing gzip files" OFF)
option(USE-MPI "Enable the use of MPI" OFF)
option(USE-OPENMP "Enable the use of OpenMP" OFF)
option(PYEXT "Compile the python extension to ResBos" OFF)
option(FITTING "Enable Nonpert fittings" OFF)
if(FITTING AND NOT USE-ROOT) 
    MESSAGE(FATAL_ERROR  "Non-perturbative fitting requires ROOT libraries")
endif(FITTING AND NOT USE-ROOT)
option(USE-CPACK "Enable packaging with CPack" OFF)

function(load_options project_name)
    if(USE-ROOT)
        add_root(${project_name})
    else()
        MESSAGE(STATUS "Building ResBos without ROOT.")
        target_compile_features(${project_name} INTERFACE cxx_std_11)
    endif()

    if(USE-YODA)
        add_yoda(${project_name})
    else()
        message(STATUS "Building ResBos without YODA.")
    endif()

    if(USE-GZIP)
        add_gzip(${project_name})
    else()
        MESSAGE(STATUS "Building without GZIP support")
    endif()

    if(USE-MPI)
        add_mpi(${project_name})
    else()
        message(STATUS "Building ResBos without MPI")
    endif()

    if(USE-OPENMP)
        add_openmp(${project_name})
    else()
        message(STATUS "Building ResBos without OpenMP")
    endif()

    # TODO: Add pyext using pybind11

endfunction()

function(add_root project_name)
    MESSAGE(STATUS "Building with ROOT histograms")
    list(APPEND CMAKE_PREFIX_PATH $ENV{ROOTSYS})
    find_package(ROOT)
    if(NOT ROOT_FOUND)
        message(FATAL_ERROR "Failed to find ROOT environment"
            " (use -DUSE-ROOT=OFF if you didn't want to build with ROOT).")
    endif(NOT ROOT_FOUND)
    include(${ROOT_USE_FILE})
    target_link_libraries(${project_name} INTERFACE ${ROOT_LIBRARIES})
    string(REPLACE "." ";" VERSION_LIST ${ROOT_VERSION})
    list(GET VERSION_LIST 0 ROOT_MAJOR_VERSION)
    MESSAGE(STATUS "ROOT VERSION: ${ROOT_VERSION}")
    if(${ROOT_MAJOR_VERSION} EQUAL 6)
        add_definitions(-DROOT6)
    elseif(${ROOT_MAJOR_VERSION} EQUAL 5)
        add_definitions(-DROOT5)
    endif(${ROOT_MAJOR_VERSION} EQUAL 6)
    if(${ROOT_CXX_FLAGS} MATCHES "[std=c++14]+")
        MESSAGE(STATUS "ROOT Build with c++14")
        MESSAGE(STATUS "Checking for c++14")
        target_compile_features(${project_name} INTERFACE cxx_std_17)
    elseif(${ROOT_CXX_FLAGS} MATCHES "[std=c++17]+")
        MESSAGE(STATUS "ROOT Build with c++17")
        MESSAGE(STATUS "Checking for c++17")
        target_compile_features(${project_name} INTERFACE cxx_std_17)
    endif()
    add_definitions(-DHAVE_ROOT)
endfunction()

function(add_yoda project_name)
    MESSAGE(STATUS "Building with YODA histograms.")
    find_package(YODA)
    if(NOT YODA_FOUND)
        message(FATAL_ERROR "Failed to find YODA environment"
            " (use -DUSE-YODA=OFF if you didn't want to build with YODA).")
    endif(NOT YODA_FOUND)
    add_definitions(-DHAVE_YODA)
    target_link_libraries(${project_options} INTERFACE ${YODA_LIBRARY})
endfunction()

function(add_gzip project_name)
    MESSAGE(STATUS "Building with GZIP capabilities")
    find_package(ZLIB)
    if(NOT ZLIB_FOUND)
        message(FATAL_ERROR "Failed to find GZIP"
            " (use -DUSE-GZIP=OFF if you didn't want to build with GZIP).")
    endif(NOT ZLIB_FOUND)
    add_definitions(-DHAVE_GZIP)
    target_link_libraries(${project_name} INTERFACE ZLIB::ZLIB)
endfunction()

function(add_mpi project_name)
    MESSAGE(STATUS "Building ResBos with MPI")
    find_package(MPI)
    if(NOT MPI_FOUND)
        message(FATAL_ERROR "Failed to find MPI"
            " (use -DUSE-MPI=OFF if you didn't want to build with MPI).")
    endif(NOT MPI_FOUND)
    add_definitions(-DUSING_MPI)
    target_link_libraries(${project_name} INTERFACE MPI::MPI_C)
endfunction()

function(add_openmp project_name)
    MESSAGE(STATUS "Building ResBos with OpenMP")
    find_package(OpenMP)
    if(NOT OPENMP_FOUND)
        message(FATAL_ERROR "Failed to find OPENMP"
            " (use -DUSE-OPENMP=OFF if you didn't want to build with OPENMP).")
    endif()
    add_definitions(-DUSING_OPENMP)
    target_link_libraries(${project_name} INTERFACE OpenMP::OpenMP_CXX)
endfunction()
